baseURL = "/"
languageCode = "en-us"
title = "Taccoform"
theme = "m10c"
googleAnalytics = "UA-181070094-1"

[params]
  author = "Joe Perez"
  description = "Tacos+Terraform"
  [[params.social]]
    name = "github"
    url = "https://github.com/jperez3"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/taccoform"
