version: '3.8'
services:
 blog:
    container_name: blog
    restart: always
    image: klakegg/hugo:0.74.3
    command: server --appendPort=false -b www.taccoform.com
    volumes:
      - "./hugo:/src"
    ports:
      - "1313:1313"
 nginx:
  container_name: nginx
  restart: always
  image: nginx:alpine
  volumes:
   - ./nginx/blog.conf:/etc/nginx/conf.d/default.conf:ro
  ports:
   - "80:80"