name: "taccoform-drift"

on:
  schedule:
    - cron: '15,20,25,30 * * * *'

# on:
#   workflow_dispatch:
#     inputs:
#       service:
#         required: false
#         default: 'taco'

env:
  TF_VERSION: 0.14.11

defaults:
  run:
    working-directory: terraform/app

jobs:
  drift:
    name: "Terraform"
    runs-on: ubuntu-20.04    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}       

      - name: Terraform Version
        id: version
        run: terraform version

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_VAR_do_token: ${{ secrets.TF_VAR_DO_TOKEN }}
          TF_VAR_do_access_id: ${{ secrets.DO_ACCESS_ID }}
          TF_VAR_do_secret_key: ${{ secrets.DO_SECRET_KEY }}
        

      - name: Terraform Plan
        id: plan
        run: terraform plan -detailed-exitcode
        continue-on-error: true
        env:
          TF_VAR_do_token: ${{ secrets.TF_VAR_DO_TOKEN }}
          TF_VAR_do_access_id: ${{ secrets.DO_ACCESS_ID }}
          TF_VAR_do_secret_key: ${{ secrets.DO_SECRET_KEY }}
        

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: |
          echo "Drift detected on this terraform workspace"
          exit 1

